# Generated by Django 3.1.2 on 2020-10-27 20:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollower',
            unique_together={('user', 'follower')},
        ),
    ]
